export const ALL_TOPPINGS_REQUEST = 'ALL_TOPPINGS_REQUEST'
export const ALL_TOPPINGS_SUCCESS = 'ALL_TOPPINGS_SUCCESS'
export const ALL_TOPPINGS_FAIL = 'ALL_TOPPINGS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'