export const ALL_TOPPINGS_REQUEST = 'ALL_TOPPINGS_REQUEST'
export const ALL_TOPPINGS_SUCCESS = 'ALL_TOPPINGS_SUCCESS'
export const ALL_TOPPINGS_FAIL = 'ALL_TOPPINGS_FAIL'

export const NEW_TOPPING_REQUEST = 'NEW_TOPPING_REQUEST'
export const NEW_TOPPING_SUCCESS = 'NEW_TOPPING_SUCCESS'
export const NEW_TOPPING_RESET = 'NEW_TOPPING_RESET'
export const NEW_TOPPING_FAIL = 'NEW_TOPPING_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'